name: LinkPortals
main: com.lith.linkportals.Plugin

version: 0.0.0
api-version: 1.20

description: A MineCraft plugin to allow linking portals
author: Lith
website: https://github.com/ImLith/MC-LinkPortals

depend: [LithCore]
softdepend: []
